In [47]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

C:\Users\Saurabh\Documents\Quant Projects\QuantLab

In [48]:
import pandas as pd

from src.data_preparation import DataPreparation

In [49]:
universe = (
    pd.read_csv("../config/universe.csv")
    ["Ticker"]
    .tolist()
)

print("Universe")

print(universe)

print(f"\nTotal Stocks: {len(universe)}")

Universe
['AAPL', 'MSFT', 'NVDA', 'AMZN', 'GOOGL', 'JPM', 'JNJ', 'XOM', 'KO', 'TSLA']

Total Stocks: 10

In [51]:
raw_data = pd.read_csv(
    "../data/raw/sp500_raw.csv"
)

raw_data.head()

  Ticker        Date   Open   High    Low  Close  Adj Close   Volume
0      A  2000-01-03  47.07  47.18  40.27  43.04      43.04  4674353
1      A  2000-01-04  40.72  41.17  38.70  39.75      39.75  4765083
2      A  2000-01-05  39.60  39.75  36.05  37.28      37.28  5758642
3      A  2000-01-06  36.83  37.06  34.74  35.86      35.86  2534434
4      A  2000-01-07  35.30  39.41  35.27  38.85      38.85  2819626

In [52]:
print("="*60)
print("RAW DATASET")
print("="*60)

print(f"Rows       : {raw_data.shape[0]}")
print(f"Columns    : {raw_data.shape[1]}")

print("\nColumn Names")

print(raw_data.columns.tolist())

============================================================
RAW DATASET
============================================================
Rows       : 2703531
Columns    : 8

Column Names
['Ticker', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

In [53]:
missing = (
    raw_data
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing[missing > 0]

Series([], dtype: int64)

In [54]:
raw_data.dtypes

Ticker        object
Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [55]:
raw_data["Date"] = pd.to_datetime(raw_data["Date"])

print(raw_data["Date"].min())
print(raw_data["Date"].max())

2000-01-03 00:00:00
2026-02-20 00:00:00

In [56]:
prep = DataPreparation(universe)

In [57]:
prices = prep.prepare_price_matrix(
    raw_data
)

prices.head()

Ticker      AAPL  AMZN  GOOGL    JNJ    JPM     KO   MSFT  NVDA  TSLA    XOM
Date
2000-01-03  0.84  4.47    NaN  23.41  22.91  13.61  35.60  0.09   NaN  17.14
2000-01-04  0.77  4.10    NaN  22.55  22.41  13.63  34.40  0.09   NaN  16.81
2000-01-05  0.78  3.49    NaN  22.79  22.27  13.75  34.76  0.08   NaN  17.73
2000-01-06  0.71  3.28    NaN  23.50  22.59  13.77  33.60  0.08   NaN  18.65
2000-01-07  0.75  3.48    NaN  24.50  23.00  14.67  34.04  0.08   NaN  18.59

In [58]:
prep.validate_price_matrix(
    prices
)

============================================================
PRICE MATRIX VALIDATION
============================================================
Rows          : 6573
Columns       : 10
Start Date    : 2000-01-03
End Date      : 2026-02-20

Missing Values
Ticker
AAPL        0
AMZN        0
GOOGL    1162
JNJ         0
JPM         0
KO          0
MSFT        0
NVDA        0
TSLA     2637
XOM         0
dtype: int64

Duplicate Dates
0

Data Types
Ticker
AAPL     float64
AMZN     float64
GOOGL    float64
JNJ      float64
JPM      float64
KO       float64
MSFT     float64
NVDA     float64
TSLA     float64
XOM      float64
dtype: object

In [59]:
prices = prep.handle_missing_values(
    prices,
    method="ffill"
)

In [60]:
prices.isna().sum()

Ticker
AAPL        0
AMZN        0
GOOGL    1162
JNJ         0
JPM         0
KO          0
MSFT        0
NVDA        0
TSLA     2637
XOM         0
dtype: int64

In [61]:
prices.head()

Ticker      AAPL  AMZN  GOOGL    JNJ    JPM     KO   MSFT  NVDA  TSLA    XOM
Date
2000-01-03  0.84  4.47    NaN  23.41  22.91  13.61  35.60  0.09   NaN  17.14
2000-01-04  0.77  4.10    NaN  22.55  22.41  13.63  34.40  0.09   NaN  16.81
2000-01-05  0.78  3.49    NaN  22.79  22.27  13.75  34.76  0.08   NaN  17.73
2000-01-06  0.71  3.28    NaN  23.50  22.59  13.77  33.60  0.08   NaN  18.65
2000-01-07  0.75  3.48    NaN  24.50  23.00  14.67  34.04  0.08   NaN  18.59

In [62]:
prices.tail()

Ticker,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2026-02-13,255.78,198.79,305.72,243.45,302.55,78.68,401.32,182.81,417.44,148.45
2026-02-17,263.88,201.15,302.02,243.33,307.13,79.56,396.86,184.97,410.63,146.19
2026-02-18,264.35,204.79,303.33,244.99,308.78,79.49,399.60,187.98,411.32,150.68
2026-02-19,260.58,204.86,302.85,246.91,308.05,78.91,398.46,187.90,411.71,150.97
2026-02-20,264.58,210.11,314.98,242.49,310.79,79.84,397.23,189.82,411.82,147.28

In [63]:
prices.describe()

Ticker,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
count,6573.000000,6573.000000,5411.000000,6573.000000,6573.000000,6573.000000,6573.000000,6573.000000,3936.000000,6573.000000
mean,49.457202,51.357073,56.829512,76.002343,66.562708,29.137227,101.015054,14.949878,102.011946,49.591877
std,70.874844,67.273477,61.109655,48.935520,65.601701,17.329604,132.664688,38.140723,128.431621,26.221526
min,0.200000,0.300000,2.480000,17.450000,8.090000,9.420000,11.140000,0.060000,1.050000,14.000000
25%,2.160000,2.460000,13.300000,35.270000,23.730000,13.420000,19.030000,0.280000,12.877500,31.060000
50%,16.020000,12.970000,29.550000,51.400000,33.100000,25.600000,26.030000,0.470000,20.075000,47.480000
75%,52.330000,91.160000,77.625000,114.720000,90.860000,39.720000,129.170000,6.040000,211.907500,56.930000
max,285.920000,254.000000,343.690000,246.910000,334.610000,79.840000,541.060000,207.030000,489.880000,154.530000

In [64]:
prep.save_dataset(
    prices,
    "../data/raw/daily_prices.csv"
)

Dataset saved to:
../data/raw/daily_prices.csv

In [65]:
prices = pd.read_csv(
    "../data/raw/daily_prices.csv",
    index_col=0,
    parse_dates=True
)

prices.head()

            AAPL  AMZN  GOOGL    JNJ    JPM     KO   MSFT  NVDA  TSLA    XOM
Date
2000-01-03  0.84  4.47    NaN  23.41  22.91  13.61  35.60  0.09   NaN  17.14
2000-01-04  0.77  4.10    NaN  22.55  22.41  13.63  34.40  0.09   NaN  16.81
2000-01-05  0.78  3.49    NaN  22.79  22.27  13.75  34.76  0.08   NaN  17.73
2000-01-06  0.71  3.28    NaN  23.50  22.59  13.77  33.60  0.08   NaN  18.65
2000-01-07  0.75  3.48    NaN  24.50  23.00  14.67  34.04  0.08   NaN  18.59

In [66]:
print("="*60)
print("FINAL DATASET")
print("="*60)

print(f"Rows      : {prices.shape[0]}")
print(f"Columns   : {prices.shape[1]}")

print(f"\nStart Date : {prices.index.min().date()}")
print(f"End Date   : {prices.index.max().date()}")

print("\nTickers")

print(prices.columns.tolist())

============================================================
FINAL DATASET
============================================================
Rows      : 6573
Columns   : 10

Start Date : 2000-01-03
End Date   : 2026-02-20

Tickers
['AAPL', 'AMZN', 'GOOGL', 'JNJ', 'JPM', 'KO', 'MSFT', 'NVDA', 'TSLA', 'XOM']

# Summary

This notebook performs the complete data preparation stage for QuantLab.

Workflow

1. Load the investment universe
2. Load the raw S&P 500 dataset
3. Convert dates
4. Filter the selected universe
5. Create a daily adjusted close price matrix
6. Validate the data
7. Handle missing values
8. Save the processed dataset

Output