In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

from src.pipeline import ResearchPipeline

In [3]:
prices = pd.read_csv(
    "../data/raw/daily_prices.csv",
    index_col=0,
    parse_dates=True
)

In [4]:
from src.strategies.momentum import MomentumStrategy

strategy = MomentumStrategy(
    lookback=13,
    top_n=5,
    bottom_n=5
)

pipeline = ResearchPipeline(
    strategy=strategy
)

results = pipeline.run(prices)

In [5]:
results["strategy_returns"].head()

Date
2000-01-07    0.0
2000-01-14    0.0
2000-01-21    0.0
2000-01-28    0.0
2000-02-04    0.0
Freq: W-FRI, dtype: float64

In [6]:
results["weights"].head()

            AAPL  AMZN  GOOGL  JNJ  JPM   KO  MSFT  NVDA  TSLA  XOM
Date
2000-01-07   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-14   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-21   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-28   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-02-04   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0

In [7]:
signals = results["signals"]

In [8]:
results["signals"].head()
results["weights"].head()

            AAPL  AMZN  GOOGL  JNJ  JPM   KO  MSFT  NVDA  TSLA  XOM
Date
2000-01-07   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-14   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-21   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-01-28   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0
2000-02-04   0.0   0.0    0.0  0.0  0.0  0.0   0.0   0.0   0.0  0.0

In [9]:
strategy = MomentumStrategy(
    lookback=13,
    top_n=5,
    bottom_n=5
)
pipeline = ResearchPipeline(
    strategy=strategy)

print(strategy.lookback)
print(strategy.top_n)
print(strategy.bottom_n)

13
5
5

In [10]:
#Checks

In [11]:
results["signals"].iloc[15:20]

            AAPL  AMZN  GOOGL  JNJ  JPM  KO  MSFT  NVDA  TSLA  XOM
Date
2000-04-21     1    -1      0    1    1  -1    -1     1     0    1
2000-04-28     1    -1      0    1    1  -1    -1     1     0    1
2000-05-05     1    -1      0    1    1  -1    -1     1     0    1
2000-05-12     1    -1      0    1   -1   1    -1     1     0    1
2000-05-19    -1    -1      0    1    1   1    -1     1     0    1

In [12]:
results["weights"].iloc[15:20]

,AAPL,AMZN,GOOGL,JNJ,JPM,KO,MSFT,NVDA,TSLA,XOM
Date,,,,,,,,,,
2000-04-21,0.200000,-0.333333,0.0,0.2,0.200000,-0.333333,-0.333333,0.2,0.0,0.2
2000-04-28,0.200000,-0.333333,0.0,0.2,0.200000,-0.333333,-0.333333,0.2,0.0,0.2
2000-05-05,0.200000,-0.333333,0.0,0.2,0.200000,-0.333333,-0.333333,0.2,0.0,0.2
2000-05-12,0.200000,-0.333333,0.0,0.2,-0.333333,0.200000,-0.333333,0.2,0.0,0.2
2000-05-19,-0.333333,-0.333333,0.0,0.2,0.200000,0.200000,-0.333333,0.2,0.0,0.2

In [13]:
(results["signals"] == 1).sum(axis=1).iloc[15:20]

Date
2000-04-21    5
2000-04-28    5
2000-05-05    5
2000-05-12    5
2000-05-19    5
Freq: W-FRI, dtype: int64

In [14]:
(results["signals"] == -1).sum(axis=1).iloc[15:20]

Date
2000-04-21    3
2000-04-28    3
2000-05-05    3
2000-05-12    3
2000-05-19    3
Freq: W-FRI, dtype: int64

In [15]:
results["signals"].head()

            AAPL  AMZN  GOOGL  JNJ  JPM  KO  MSFT  NVDA  TSLA  XOM
Date
2000-01-07     0     0      0    0    0   0     0     0     0    0
2000-01-14     0     0      0    0    0   0     0     0     0    0
2000-01-21     0     0      0    0    0   0     0     0     0    0
2000-01-28     0     0      0    0    0   0     0     0     0    0
2000-02-04     0     0      0    0    0   0     0     0     0    0

In [16]:
(results["signals"] == 1).sum(axis=1)

Date
2000-01-07    0
2000-01-14    0
2000-01-21    0
2000-01-28    0
2000-02-04    0
             ..
2026-01-23    5
2026-01-30    5
2026-02-06    5
2026-02-13    5
2026-02-20    5
Freq: W-FRI, Length: 1364, dtype: int64